kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-namespace-viewer
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-binding
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
subjects:
- kind: Group
  name: system:masters
  namespace: default
roleRef:
  kind: Role
  name: user-namespace-viewer
  apiGroup: rbac.authorization.k8s.io
